Update action.yml

diff --git a/nbdev-mkdocs-ghp/action.yml b/nbdev-mkdocs-ghp/action.yml
--- a/nbdev-mkdocs-ghp/action.yml
+++ b/nbdev-mkdocs-ghp/action.yml
@@ -61,7 +61,10 @@ runs:
       shell: bash
       run: |
         git ls-remote --exit-code --heads origin 'gh-pages' >/dev/null 2>&1
-        echo "GH_PAGES_ERROR_CODE=$?" >> $GITHUB_ENV
+        exit_code=$?
+        echo "Printing exit code: ${exit_code}"
+        echo "GH_PAGES_ERROR_CODE=$exit_code" >> $GITHUB_ENV
+        echo "Printing exit code in github env: ${ env.GH_PAGES_ERROR_CODE }"
     - name: Deploy to GitHub Pages
       if: ${{ env.DOCS_VERSIONING == '' || env.DOCS_VERSIONING == 'None' || env.GH_PAGES_ERROR_CODE == '2'}}
       uses: peaceiris/actions-gh-pages@v3
